"""
SPARTAN v2.0 — Protocol Vulnerabilities Index
Auto-generated from ~10,600 DeFi security audit findings.
Source: github.com/kadenzipfel/protocol-vulnerabilities-index

460 categories across 31 protocol types.
Used by SPARTAN to perform protocol-type-aware vulnerability lookups.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ProtocolVulnCategory:
    name: str
    slug: str
    description: str
    detection_hints: list[str] = field(default_factory=list)
    attack_patterns: list[str] = field(default_factory=list)
    remediation: str = ""
    references: list[str] = field(default_factory=list)


@dataclass
class ProtocolType:
    name: str
    slug: str
    description: str
    categories: list[ProtocolVulnCategory]

    def get_checklist(self) -> str:
        lines = [f"## {self.name} — Vulnerability Checklist ({len(self.categories)} categories)\n"]
        for c in self.categories:
            lines.append(f"- [ ] **{c.name}**")
        return "\n".join(lines)

    def get_category(self, name: str) -> Optional[ProtocolVulnCategory]:
        name_lower = name.lower()
        return next((c for c in self.categories if name_lower in c.name.lower()), None)


# ── Protocol Type Definitions ─────────────────────────────────────────────────

PROTOCOL_INDEX: dict[str, ProtocolType] = {

    # ── ALGO STABLES ──────────────────────────────────────────────────────────
    "algo-stables": ProtocolType(
        name="Algo Stables",
        slug="algo-stables",
        description="Algorithmic stablecoin protocols maintaining peg via mint/burn or rebasing mechanisms.",
        categories=[
            ProtocolVulnCategory("Access Control Missing", "access-control-missing",
                "Missing onlyOwner/onlyRole modifiers on privileged mint, burn, or peg-management functions.",
                ["Public mint/burn functions", "Peg management without access controls"],
                ["Call mint() without authorization to inflate supply"],
                "Apply role-based access control to all state-changing governance and treasury functions.",
                ["SWC-105"]),
            ProtocolVulnCategory("AMM Price Manipulation", "amm-price-manipulation",
                "Protocol uses AMM spot price to determine stablecoin peg or collateral value, enabling flash-loan manipulation.",
                ["Spot price from Uniswap/Curve used for peg calculations", "No TWAP oracle"],
                ["Flash borrow → drain AMM reserves → trigger peg rebalance at manipulated price"],
                "Use TWAP oracle with sufficient observation window (≥30min) or Chainlink price feeds.",
                ["https://docs.uniswap.org/concepts/protocol/oracle"]),
            ProtocolVulnCategory("Epoch Share Accounting", "epoch-share-accounting",
                "Incorrect share or reward accounting across epoch boundaries allows double-claiming or loss of rewards.",
                ["Epoch-based reward snapshots", "Share balance calculated at wrong checkpoint"],
                ["Stake at end of epoch → claim from epoch where shares not held"],
                "Ensure shares/rewards are snapshotted at epoch start and properly attributed.",
                []),
            ProtocolVulnCategory("Governance Vote Manipulation", "governance-vote-manipulation",
                "Flash-loan or checkpoint attacks allow governance takeover without long-term token holding.",
                ["Token borrowable and usable for governance in same block"],
                ["Flash borrow → vote → repay"],
                "Lock voting power at proposal creation; require holding period before voting.",
                []),
            ProtocolVulnCategory("Missing Slippage Protection", "missing-slippage-protection",
                "Swap or rebalance operations lack amountOutMin, enabling sandwich attacks.",
                ["swap() calls with amountOutMin=0", "No deadline parameter"],
                ["Sandwich attack on protocol's own rebalance transaction"],
                "Enforce minimum output amounts and deadline timestamps on all AMM interactions.",
                []),
            ProtocolVulnCategory("Oracle Stale Price", "oracle-stale-price",
                "Protocol uses Chainlink price feed without checking updatedAt timestamp, accepting stale data.",
                ["latestRoundData() without staleness check", "No heartbeat validation"],
                ["If oracle paused or sequencer down, stale price used for critical calculations"],
                "Check updatedAt + heartbeat; revert if price is stale.",
                ["https://docs.chain.link/data-feeds"]),
            ProtocolVulnCategory("Reentrancy", "reentrancy",
                "External token callbacks (ERC-777, safeTransfer) allow reentrant calls before state updates.",
                ["State updates after external calls", "ERC-777 hooks exploitable"],
                ["Re-enter mint() during callback before balance decremented"],
                "Follow Checks-Effects-Interactions. Use ReentrancyGuard.",
                ["SWC-107"]),
            ProtocolVulnCategory("Reward Distribution Accounting", "reward-distribution-accounting",
                "Reward calculations using balances that can be manipulated mid-distribution.",
                ["totalSupply() or balanceOf() used in reward formula", "Balance snapshotted after manipulation possible"],
                ["Flash mint stablecoins → distort ratio → claim outsized rewards → burn"],
                "Use immutable snapshots or time-weighted balances for reward calculations.",
                []),
            ProtocolVulnCategory("Stale Protocol State", "stale-protocol-state",
                "Protocol relies on cached or delayed state that diverges from actual state, enabling arbitrage.",
                ["Cached collateral ratio not updated per block", "Staleness window allows gaming"],
                ["Exploit gap between actual and reported collateral ratio"],
                "Update critical state variables before any operation that reads them.",
                []),
            ProtocolVulnCategory("Token Decimal Mismatch", "token-decimal-mismatch",
                "Protocol assumes all tokens use 18 decimals, causing accounting errors with 6-decimal (USDC) or non-standard tokens.",
                ["Hardcoded 1e18 in math without decimal normalization", "USDC/USDT 6-decimal incompatibility"],
                ["Deposit USDC → protocol treats as 1e-12 of actual value → mint 10^12x stablecoins"],
                "Normalize all token amounts to a common precision before arithmetic.",
                []),
            ProtocolVulnCategory("Unsafe ERC20 Operations", "unsafe-erc20-operations",
                "Using transfer/transferFrom without checking return value may silently fail with non-standard tokens.",
                ["token.transfer() without return value check", "Non-standard ERC20 tokens (USDT, BNB)"],
                ["USDT transfer fails silently → protocol misaccounts balance"],
                "Use SafeERC20 library for all token transfers.",
                ["https://github.com/OpenZeppelin/openzeppelin-contracts"]),
            ProtocolVulnCategory("Unsafe NFT Minting", "unsafe-nft-minting",
                "NFT minting with safeMint to untrusted receiver allows reentrancy via onERC721Received callback.",
                ["_safeMint() to user-supplied address", "State updated after mint"],
                ["Deploy contract with malicious onERC721Received that re-enters mint"],
                "Use _mint() instead of _safeMint() when minting to protocol-internal addresses, or apply ReentrancyGuard.",
                []),
        ],
    ),

    # ── BRIDGE ────────────────────────────────────────────────────────────────
    "bridge": ProtocolType(
        name="Bridge",
        slug="bridge",
        description="Cross-chain bridging protocols for asset transfers between L1/L2 and different chains.",
        categories=[
            ProtocolVulnCategory("Access Control Misconfiguration", "access-control-misconfiguration",
                "Admin or validator functions accessible to unauthorized callers.",
                ["setAdmin/setValidator without multisig", "Relayer keys with insufficient protection"],
                ["Call admin function directly to add malicious validator"],
                "Use multi-sig with high threshold for all privileged bridge functions. Implement timelocks.",
                []),
            ProtocolVulnCategory("Arithmetic and Precision Errors", "arithmetic-and-precision-errors",
                "Integer overflow, underflow, or precision loss in fee calculations or amount conversions.",
                ["Division before multiplication causing precision loss", "Unchecked arithmetic in fee math"],
                ["Submit transfer with crafted amount that overflows fee calculation to 0"],
                "Use Solidity 0.8+ built-in checks. Multiply before dividing. Validate bounds.",
                []),
            ProtocolVulnCategory("Cross Chain Message Replay", "cross-chain-message-replay",
                "Bridge messages can be replayed on the destination chain or across chain forks.",
                ["nonce not included in message hash", "chainId not in domain separator", "Message not marked as processed"],
                ["Replay valid unlock message to drain bridge funds twice"],
                "Include nonce, chainId, and contractAddress in all message hashes. Mark messages as processed atomically.",
                ["SWC-121"]),
            ProtocolVulnCategory("Denial of Service", "denial-of-service",
                "Attacker can grief the bridge by blocking message processing or exhausting gas.",
                ["Unbounded arrays in message processing", "Low-value message spam"],
                ["Flood bridge with minimal messages to exhaust relayer gas/funds"],
                "Implement message size limits, gas estimation, and per-user rate limiting.",
                []),
            ProtocolVulnCategory("ERC4626 Vault Share Issues", "erc4626-vault-share-issues",
                "Vault share inflation attack or incorrect share accounting in bridged vault tokens.",
                ["First depositor can inflate share price", "Share calculations using raw balanceOf"],
                ["Donate tokens directly to vault to inflate share price before others deposit"],
                "Add virtual shares defense (OpenZeppelin v5 ERC4626). Use internal accounting.",
                ["https://blog.openzeppelin.com/a-novel-defense-against-erc4626-inflation-attacks"]),
            ProtocolVulnCategory("External Call Injection", "external-call-injection",
                "Bridge executes arbitrary calls from message payload without proper validation.",
                ["Call data from message passed to low-level call()", "Target address from user-supplied message"],
                ["Craft message with call to arbitrary contract → steal funds from bridge"],
                "Use strict allowlists for callable contracts and function selectors.",
                []),
            ProtocolVulnCategory("Flow Rate and Rate Limiting", "flow-rate-and-rate-limiting",
                "No circuit breaker limits on bridge outflows allow large drain in single transaction.",
                ["No per-block or per-window withdrawal caps", "Unlimited single-transaction withdrawals"],
                ["Single 100M USDC withdrawal bridged before circuit breaker triggers"],
                "Implement time-based rate limits and per-transaction caps. Add emergency pause.",
                []),
            ProtocolVulnCategory("Funds Locked in Contracts", "funds-locked-in-contracts",
                "State machine flaws or missing recovery functions leave funds permanently locked in bridge.",
                ["No rescue function for failed messages", "Terminal state without recovery"],
                ["Message fails processing → funds stuck with no recovery path"],
                "Implement message retry mechanisms and emergency fund recovery functions.",
                []),
            ProtocolVulnCategory("Gas Limit and Estimation", "gas-limit-and-estimation",
                "Insufficient gas forwarded to destination chain cause message execution failures.",
                ["Fixed gas limits in cross-chain calls", "No gas estimation for variable-length data"],
                ["Craft message that hits gas limit exactly on destination → partial execution"],
                "Use dynamic gas estimation. Forward sufficient gas or implement retry logic for failed executions.",
                []),
            ProtocolVulnCategory("Initialization and Upgrade Flaws", "initialization-and-upgrade-flaws",
                "Proxy initialization callable by anyone or upgrade storage collision vulnerabilities.",
                ["initialize() without initializer modifier", "Storage collision between proxy and impl"],
                ["Call initialize() on deployed proxy to become owner"],
                "Use OZ Initializable modifier. Follow EIP-1967 storage slot standards.",
                ["SWC-124"]),
            ProtocolVulnCategory("Insufficient Input Validation", "insufficient-input-validation",
                "Bridge fails to validate message contents, allowing malicious payloads.",
                ["No validation on token address, amount, or recipient in messages"],
                ["Send message with zero-address recipient or token to lock funds"],
                "Validate all message fields (non-zero addresses, bounded amounts, valid token contracts).",
                []),
            ProtocolVulnCategory("Native ETH Handling", "native-eth-handling",
                "Incorrect handling of msg.value vs token amounts, or ETH getting locked in contracts.",
                ["msg.value not refunded on partial failures", "ETH mixed with ERC20 accounting"],
                ["Send ETH with msg.value but protocol uses only token balance → ETH locked"],
                "Refund excess msg.value on failure. Separate ETH and ERC20 accounting paths.",
                []),
            ProtocolVulnCategory("Non Standard Token Handling", "non-standard-token-handling",
                "Fee-on-transfer, rebasing, or ERC-777 tokens cause accounting discrepancies in bridge.",
                ["Protocol assumes received amount equals transferred amount"],
                ["Bridge fee-on-transfer token → receive less than sent → protocol misaccounts"],
                "Measure actual balance delta after transfer. Blacklist problematic token types or handle explicitly.",
                []),
            ProtocolVulnCategory("Oracle and Price Feed Issues", "oracle-and-price-feed-issues",
                "Stale or manipulable price feeds used for cross-chain asset valuations.",
                ["Single oracle source", "No staleness check on price feed"],
                ["Oracle goes stale during network congestion → bridge uses wrong conversion rate"],
                "Use aggregated price feeds with staleness checks. Implement circuit breakers.",
                []),
            ProtocolVulnCategory("Reentrancy", "reentrancy",
                "ETH or token callbacks during bridge execution enable reentrant message processing.",
                ["ETH transfer before state update in bridge logic", "Token callback before marking message processed"],
                ["Reenter bridge during ETH callback to replay message before processed flag set"],
                "Mark messages as processed BEFORE sending assets. Use ReentrancyGuard.",
                ["SWC-107"]),
            ProtocolVulnCategory("Slippage and Price Manipulation", "slippage-and-price-manipulation",
                "Bridge AMM swaps on destination chain with no slippage protection.",
                ["amountOutMin not enforced on destination swap", "Sandwich-able bridge swap"],
                ["Sandwich the bridge's destination AMM swap to extract value"],
                "Enforce minimum output amounts on all bridge-initiated swaps. Use time-weighted prices.",
                []),
            ProtocolVulnCategory("State Update Inconsistency", "state-update-inconsistency",
                "State updates on source and destination chains become inconsistent due to failed messages or reorgs.",
                ["Optimistic message passing without finality guarantees", "Reorg risk on source chain"],
                ["Trigger reorg on source chain after bridge message sent → double spend"],
                "Wait for full finality before processing cross-chain messages. Implement rollback recovery.",
                []),
            ProtocolVulnCategory("Unchecked Return Values", "unchecked-return-values",
                "Return values from external calls not checked, causing silent failures.",
                ["bool success = token.transfer() without require(success)", "low-level .call() return not checked"],
                ["Transfer fails silently → bridge state updated as if successful"],
                "Use SafeERC20. Always check return values from external token calls.",
                ["CWE-252"]),
        ],
    ),

    # ── CDP ───────────────────────────────────────────────────────────────────
    "cdp": ProtocolType(
        name="CDP (Collateralized Debt Protocol)",
        slug="cdp",
        description="Protocols where users lock collateral to mint synthetic assets or stablecoins.",
        categories=[
            ProtocolVulnCategory("Access Control Bypass", "access-control-bypass",
                "Unauthorized callers can invoke mint, liquidate, or parameter-setting functions.",
                ["missing onlyOwner/onlyRole on critical functions"],
                ["Call setCollateralRatio() to set ratio to 0 → drain protocol"],
                "Strict role-based access control on all privileged functions.",
                []),
            ProtocolVulnCategory("Flash Loan Attacks", "flash-loan-attacks",
                "Flash loans used to manipulate collateral price or governance to drain CDP protocol.",
                ["Spot price used for collateral valuation", "No flash loan protection on liquidations"],
                ["Flash borrow → dump collateral → trigger mass undercollateralized liquidations → profit"],
                "Use TWAP for collateral pricing. Add minimum holding periods for liquidations.",
                []),
            ProtocolVulnCategory("Liquidation Mechanism Flaws", "liquidation-mechanism-flaws",
                "Liquidation logic errors allow undercollateralized positions to persist or allow bad debt to accumulate.",
                ["No incentive for liquidators", "Missing health factor checks", "Race condition in liquidation"],
                ["Avoid liquidation by flash-inflating collateral price → extract collateral → price returns"],
                "Ensure liquidation incentives are sufficient. Use TWAP-based health checks.",
                []),
            ProtocolVulnCategory("Oracle Price Manipulation", "oracle-price-manipulation",
                "Spot price oracle for collateral manipulable via flash loans or large trades.",
                ["Uniswap V2 getAmountsOut used as price oracle"],
                ["Flash borrow → inflate collateral price → mint max stablecoin → repay → price collapses"],
                "Use Chainlink or Uniswap V3 TWAP with 30+ minute window.",
                []),
            ProtocolVulnCategory("Precision and Rounding Errors", "precision-and-rounding-errors",
                "Integer division truncation causes systematic rounding loss or allows dust exploitation.",
                ["division before multiplication", "1-wei rounding exploits in interest calculations"],
                ["Round-down exploit: borrow max that rounds interest owed to 0"],
                "Multiply before dividing. Round in protocol's favor. Use fixed-point math libraries.",
                []),
            ProtocolVulnCategory("Reentrancy", "reentrancy",
                "Reentrant calls during collateral withdrawal before debt position updated.",
                ["State update after external token transfer", "ERC-777 collateral hook"],
                ["Re-enter withdraw() before collateral balance decremented"],
                "Update all state before external transfers. Use ReentrancyGuard.",
                ["SWC-107"]),
            ProtocolVulnCategory("Reward Accounting Errors", "reward-accounting-errors",
                "Incorrect per-user reward accounting allows over-claiming or double-claiming.",
                ["Global accumulator not updated before per-user calculation"],
                ["Borrow → wait for rewards → repay → borrow again → double-claim"],
                "Update global accumulator before any per-user reward calculation.",
                []),
            ProtocolVulnCategory("Signature and Replay Vulnerabilities", "signature-and-replay-vulnerabilities",
                "Permit signatures or off-chain approvals replayable across chains or contracts.",
                ["No nonce or chainId in signed message", "Permit deadline too long"],
                ["Replay permit signature from another chain"],
                "Include nonce, chainId, and contract address in all signed messages. Short deadlines.",
                ["SWC-121"]),
            ProtocolVulnCategory("Slippage and Sandwich Attacks", "slippage-and-sandwich-attacks",
                "Protocol-triggered AMM operations lack slippage protection enabling MEV extraction.",
                ["amountOutMin not set on protocol swaps", "Large swap without price impact limit"],
                ["Sandwich the protocol's liquidation swap"],
                "Set tight slippage bounds on all protocol-initiated swaps.",
                []),
            ProtocolVulnCategory("Vault Share Inflation", "vault-share-inflation",
                "First-depositor attack on ERC-4626 style CDP vault.",
                ["First depositor can set share price arbitrarily"],
                ["Deposit 1 wei → donate large amount → subsequent depositors get 0 shares"],
                "Use virtual shares offset or enforce minimum initial deposit.",
                ["https://blog.openzeppelin.com/a-novel-defense-against-erc4626-inflation-attacks"]),
        ],
    ),

    # ── DEXES ─────────────────────────────────────────────────────────────────
    "dexes": ProtocolType(
        name="DEXes (Decentralized Exchanges)",
        slug="dexes",
        description="On-chain automated market makers, order books, and liquidity pools.",
        categories=[
            ProtocolVulnCategory("Access Control", "access-control",
                "Privileged pool or fee parameters settable by unauthorized callers.",
                ["setFee/setAdmin without access control"],
                ["Set fee to 100% → drain all swap fees"],
                "Role-based access control on all pool parameter setters.",
                []),
            ProtocolVulnCategory("Flash Loan Attacks", "flash-loan-attacks",
                "Flash loans used to manipulate DEX reserves for profit or protocol exploitation.",
                ["Spot price = reserve ratio directly used as price oracle"],
                ["Flash borrow → manipulate reserve → exploit integrated protocol → return"],
                "Offer TWAP oracle. Implement flash loan fee. Add per-block price limits.",
                []),
            ProtocolVulnCategory("Front Running and MEV", "front-running-and-mev",
                "Transactions with no slippage protection or deadline are sandwichable in the mempool.",
                ["swap() with amountOutMin=0", "No deadline parameter on LP operations"],
                ["Observe large swap → insert buy before → sell after victim's tx"],
                "Enforce non-zero amountOutMin and deadline on all swap/LP functions.",
                []),
            ProtocolVulnCategory("Griefing Attacks", "griefing-attacks",
                "Attacker can permanently grief a pool or user at low cost to themselves.",
                ["Very small deposits accepted preventing pool initialization", "JIT liquidity griefing"],
                ["Donate 1 wei to prevent first-deposit ratio from being set correctly"],
                "Enforce minimum deposit thresholds. Implement deposit lockups.",
                []),
            ProtocolVulnCategory("Incorrect Math Calculations", "incorrect-math-calculations",
                "AMM invariant-breaking arithmetic errors cause incorrect pricing or loss of funds.",
                ["k=x*y invariant violated on edge cases", "Incorrect constant product formula implementation"],
                ["Craft trade that breaks invariant to steal from pool"],
                "Rigorous mathematical proof of invariant maintenance. Fuzz test all arithmetic paths.",
                []),
            ProtocolVulnCategory("Integer Overflow Underflow", "integer-overflow-underflow",
                "Arithmetic overflow/underflow in liquidity or price calculations.",
                ["Solidity <0.8.0 without SafeMath in DEX math"],
                ["Overflow reserve calculation to wrap around and steal funds"],
                "Use Solidity 0.8+. Validate bounds before arithmetic.",
                ["SWC-101"]),
            ProtocolVulnCategory("Oracle Price Manipulation", "oracle-price-manipulation",
                "DEX price feed used by external protocols manipulable via large trades.",
                ["Thin liquidity pool used as price oracle by lending protocol"],
                ["Large trade to move thin-liquidity DEX price → exploit dependent protocol"],
                "Use Uniswap V3 TWAP with deep liquidity. Enforce minimum observation periods.",
                []),
            ProtocolVulnCategory("Reentrancy", "reentrancy",
                "ERC-777 tokenTransfer hooks or ETH callbacks allow reentrant pool manipulation.",
                ["ETH transfer in swap path before balance update", "ERC-777 hook during swap"],
                ["Re-enter swap() during ERC-777 transfer to exploit intermediate state"],
                "Update all reserves before any external token transfer.",
                ["SWC-107"]),
            ProtocolVulnCategory("Rounding and Precision Loss", "rounding-and-precision-loss",
                "Systematic rounding errors in fee or liquidity calculations benefit attackers.",
                ["fee rounded down to 0", "liquidity calculated with floor division"],
                ["Submit optimal trade size that rounds fee to 0 for repeated gas-efficient arbitrage"],
                "Round fees up in protocol's favor. Enforce minimum fee floor.",
                []),
            ProtocolVulnCategory("Signature and Replay Vulnerabilities", "signature-and-replay-vulnerabilities",
                "Order signatures replayable on different chains or after cancellation.",
                ["Order signature without chainId or nonce"],
                ["Replay cancelled limit order signature to fill at old price"],
                "Include chainId, nonce, and expiry in all order signatures.",
                []),
            ProtocolVulnCategory("Token Decimal Mismatch", "token-decimal-mismatch",
                "DEX assumes 18-decimal tokens, causing miscalculation with USDC (6 decimals) or WBTC (8 decimals).",
                ["Hardcoded 1e18 multiplier in price calculations"],
                ["USDC/WBTC pool gives wrong price due to decimal normalization failure"],
                "Normalize all amounts by token decimals before AMM math.",
                []),
            ProtocolVulnCategory("Unsafe External Calls", "unsafe-external-calls",
                "Unrestricted external calls from DEX hooks or callbacks expose attack surface.",
                ["afterSwap() hook calls arbitrary external contract", "callback to user-supplied address"],
                ["Supply malicious callback contract to execute arbitrary code during swap"],
                "Strictly validate callback targets. Use allowlist for hook contracts.",
                []),
        ],
    ),

    # ── LENDING ───────────────────────────────────────────────────────────────
    "lending": ProtocolType(
        name="Lending",
        slug="lending",
        description="Collateralized lending and borrowing protocols (Aave, Compound style).",
        categories=[
            ProtocolVulnCategory("Access Control", "access-control",
                "Unauthorized callers can modify risk parameters, interest rates, or borrow limits.",
                ["setReserveFactor/setLTV without governance guard"],
                ["Set LTV to 100% for worthless collateral → drain protocol"],
                "All parameter changes gated by governance timelock.",
                []),
            ProtocolVulnCategory("Accounting Share Mismatch", "accounting-share-mismatch",
                "Discrepancy between aToken/cToken shares and underlying asset balance causes bad debt.",
                ["Interest accrual not applied before share minting/burning"],
                ["Borrow → interest accrues → repay principal only due to stale index → leave bad debt"],
                "Accrue interest before every borrow, repay, liquidate, and deposit operation.",
                []),
            ProtocolVulnCategory("Bad Debt Insolvency", "bad-debt-insolvency",
                "Positions go underwater without being liquidated, leaving irrecoverable bad debt.",
                ["No penalty liquidation for underwater positions", "Oracle fails to update during market crash"],
                ["Price crash faster than oracle updates → positions cannot be liquidated at profit"],
                "Implement bad debt socialization mechanism. Use fast-updating oracle sources.",
                []),
            ProtocolVulnCategory("Interest Accrual Errors", "interest-accrual-errors",
                "Interest not accrued before balance reads, or compound interest formula errors.",
                ["getBalance() called before accrueInterest()", "Wrong compounding frequency"],
                ["Repeatedly borrow and repay in same tx to avoid interest accrual"],
                "Always call accrueInterest() at start of every function that reads balances.",
                []),
            ProtocolVulnCategory("Liquidation Logic", "liquidation-logic",
                "Liquidation incentives wrong, health factor calculated incorrectly, or liquidations blockable.",
                ["health factor calculation uses stale oracle", "liquidation bonus too low to be profitable"],
                ["Front-run liquidation with collateral top-up to prevent and pocket bad debt"],
                "Ensure profitable liquidation incentives. Use MEV-resistant liquidation designs.",
                []),
            ProtocolVulnCategory("Oracle Price Feed", "oracle-price-feed",
                "Stale, manipulable, or single-source oracle causes incorrect collateral valuations.",
                ["Single Chainlink feed without circuit breaker", "No L2 sequencer uptime check"],
                ["Stale oracle on L2 sequencer downtime → positions incorrectly valued"],
                "Use Chainlink with staleness checks. Verify L2 sequencer uptime. Use fallback oracles.",
                ["https://docs.chain.link/data-feeds/l2-sequencer-feeds"]),
            ProtocolVulnCategory("Position Health Check", "position-health-check",
                "Health factor miscalculated due to missing assets, wrong decimals, or stale prices.",
                ["New collateral type added without updating health check calculation"],
                ["Add new collateral not included in health check → borrow against ghost collateral"],
                "Ensure all registered collateral types are included in health factor formula.",
                []),
            ProtocolVulnCategory("Precision Loss Rounding", "precision-loss-rounding",
                "Systematic rounding favors borrowers over protocol, enabling near-zero cost borrowing.",
                ["Interest rounded down to 0 on small positions"],
                ["Open minimum borrow position with near-zero interest due to rounding"],
                "Round interest calculations in protocol's favor.",
                []),
            ProtocolVulnCategory("Reentrancy", "reentrancy",
                "Reentrant calls during borrow/repay before health check or balance update.",
                ["External token transfer before health factor validation"],
                ["Re-enter borrow() during collateral callback to borrow more than allowed"],
                "Validate health factor before external calls. Use ReentrancyGuard.",
                ["SWC-107"]),
            ProtocolVulnCategory("Vault Share Inflation", "vault-share-inflation",
                "First depositor can inflate share price to steal subsequent depositors' funds.",
                ["First deposit to empty vault determines initial share price"],
                ["Deposit 1 wei → donate 1e18 → next depositor gets 0 shares"],
                "Virtual shares defense or minimum initial deposit requirement.",
                []),
        ],
    ),

    # ── LIQUID STAKING ────────────────────────────────────────────────────────
    "liquid-staking": ProtocolType(
        name="Liquid Staking",
        slug="liquid-staking",
        description="Protocols that issue liquid staking tokens (LSTs) for staked ETH/assets.",
        categories=[
            ProtocolVulnCategory("Access Control", "access-control",
                "Validator management or reward distribution functions accessible to unauthorized callers.",
                ["addValidator/removeValidator without governance guard"],
                ["Add malicious validator to capture staking rewards"],
                "Multi-sig governance for all validator management. Timelock on parameter changes.",
                []),
            ProtocolVulnCategory("Balance Accounting", "balance-accounting",
                "LST rebase or reward accounting errors cause incorrect share-to-ETH conversions.",
                ["totalPooledEther() not updated after slashing events", "Rebase calculation errors"],
                ["Exploit stale totalPooledEther to redeem LST at pre-slash rate"],
                "Update all accounting state before and after any validator event.",
                []),
            ProtocolVulnCategory("Flash Loan Attacks", "flash-loan-attacks",
                "Flash loans used to manipulate LST/ETH ratio or governance for profit.",
                ["LST/ETH ratio calculated from spot balances"],
                ["Flash borrow ETH → deposit → ratio changes → claim → withdraw → repay"],
                "Use time-weighted ratios. Add deposit/withdrawal lockups.",
                []),
            ProtocolVulnCategory("Oracle Price Manipulation", "oracle-price-manipulation",
                "LST price oracle manipulable via large deposits or rebases.",
                ["Spot balanceOf ETH in pool used as LST price"],
                ["Large ETH donation changes ratio artificially before redemption"],
                "Use TWAP for LST/ETH conversion rates. Enforce rate bounds.",
                []),
            ProtocolVulnCategory("Reentrancy", "reentrancy",
                "ETH callbacks during staking deposit or withdrawal allow reentrant position manipulation.",
                ["ETH sent to user before state updated"],
                ["Re-enter withdraw() during ETH transfer before share burned"],
                "Burn shares before sending ETH. Use ReentrancyGuard.",
                ["SWC-107"]),
            ProtocolVulnCategory("Reward Accounting", "reward-accounting",
                "Validator rewards distributed incorrectly due to timing of snapshots.",
                ["Reward snapshot at wrong block", "new stakers receive historical rewards"],
                ["Stake just before reward distribution → receive full epoch rewards with minimal time staked"],
                "Use time-weighted reward distribution. Track stake duration.",
                []),
            ProtocolVulnCategory("Share Price Manipulation", "share-price-manipulation",
                "LST share price manipulable via direct ETH injection bypassing staking mechanism.",
                ["getSharesByPooledEth() uses raw ETH balance in contract"],
                ["Donate ETH directly to contract → inflate LST/ETH ratio → redeem at inflated rate"],
                "Use internal accounting separate from raw ETH balance.",
                []),
            ProtocolVulnCategory("Signature Replay", "signature-replay",
                "Off-chain signed validator operations replayable.",
                ["Validator deposit credential signatures without nonce"],
                ["Replay valid deposit signature to double-register validator"],
                "Include nonce and expiry in all off-chain signatures.",
                []),
            ProtocolVulnCategory("Slippage and MEV", "slippage-and-mev",
                "LST swaps on AMMs vulnerable to sandwich attacks due to no slippage protection.",
                ["LST/ETH swap without amountOutMin"],
                ["Sandwich large LST redemption on Curve"],
                "Enforce amountOutMin on all LST swaps.",
                []),
            ProtocolVulnCategory("Withdrawal Unstaking Issues", "withdrawal-unstaking-issues",
                "Withdrawal queue DoS or incorrect accounting of pending withdrawals.",
                ["Unbounded withdrawal queue array", "Pending withdrawals not tracked correctly"],
                ["Spam withdrawal requests to exhaust gas in queue processing"],
                "Cap withdrawal queue size. Track pending amounts separately from staked.",
                []),
        ],
    ),

    # ── YIELD AGGREGATOR ──────────────────────────────────────────────────────
    "yield-aggregator": ProtocolType(
        name="Yield Aggregator",
        slug="yield-aggregator",
        description="Protocols that auto-compound yields across multiple DeFi strategies.",
        categories=[
            ProtocolVulnCategory("First Depositor Share Inflation", "first-depositor-share-inflation",
                "First depositor to empty vault inflates share price to steal subsequent depositors.",
                ["Empty vault accepts first deposit of any size", "No virtual shares"],
                ["Deposit 1 wei → donate large amount → next depositor gets 0 shares"],
                "Virtual shares offset or minimum deposit amount enforced.",
                []),
            ProtocolVulnCategory("Oracle and Price Manipulation", "oracle-and-price-manipulation",
                "Yield strategy evaluation uses manipulable prices to overstate NAV.",
                ["Strategy value calculated from spot price"],
                ["Flash loan to inflate strategy value → mint excess vault shares → dump"],
                "Use TWAP for strategy valuation. Add deposit/withdrawal limits.",
                []),
            ProtocolVulnCategory("Reentrancy via Callback Tokens", "reentrancy-via-callback-tokens",
                "ERC-777 harvest callbacks allow reentrancy during compound operations.",
                ["harvest() calls external protocol before updating vault shares"],
                ["Re-enter harvest() via ERC-777 hook during compounding"],
                "Update shares before harvesting. Apply ReentrancyGuard.",
                ["SWC-107"]),
            ProtocolVulnCategory("Replay and Signature Vulnerabilities", "replay-and-signature-vulnerabilities",
                "Strategy migration or rebalance authorized by signatures replayable.",
                ["Strategy change signed without nonce"],
                ["Replay old strategy migration signature to revert to less optimal strategy and extract fee"],
                "Include nonce and expiry in all strategy change authorizations.",
                []),
            ProtocolVulnCategory("Reward Accounting Manipulation", "reward-accounting-manipulation",
                "Harvest rewards miscalculated when tokens have fee-on-transfer or rebasing mechanics.",
                ["Reward token is rebasing or fee-on-transfer"],
                ["Donate rebasing token → trigger harvest → vault receives inflated amount → shares minted for attacker"],
                "Measure actual balance delta. Separate strategy deposits from protocol-owned balance.",
                []),
            ProtocolVulnCategory("Stale Cached State Desync", "stale-cached-state-desync",
                "Strategy's cached NAV diverges from actual on-chain state, enabling stale-price arbitrage.",
                ["NAV updated only on harvest", "Price arbitrage window between harvests"],
                ["Deposit before NAV update → harvest compounding → withdraw at higher NAV"],
                "Enforce per-block NAV bounds. Add deposit/withdrawal lockup windows.",
                []),
            ProtocolVulnCategory("Upgradeable Storage Gap", "upgradeable-storage-gap",
                "Missing storage gap in upgradeable strategy contracts causes storage collision on upgrade.",
                ["No __gap variable in upgradeable base contract"],
                ["Upgrade storage collides with inherited contract's variables → state corruption"],
                "Add uint256[50] private __gap at end of every upgradeable base contract.",
                ["https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable"]),
        ],
    ),

    # ── STAKING POOL ──────────────────────────────────────────────────────────
    "staking-pool": ProtocolType(
        name="Staking Pool",
        slug="staking-pool",
        description="Token staking and reward distribution protocols.",
        categories=[
            ProtocolVulnCategory("Access Control Authorization", "access-control-authorization",
                "Unauthorized callers can set reward rates, drain treasury, or pause staking.",
                ["setRewardRate() without access control"],
                ["Set reward rate to 0 to stop accrual and claim accumulated uncollected rewards"],
                "Role-based access control. Multi-sig for privileged parameter changes.",
                []),
            ProtocolVulnCategory("Denial of Service", "denial-of-service",
                "Griefing attacks block reward claims or staking operations.",
                ["Unbounded loop over all stakers in reward distribution"],
                ["Add thousands of 1-wei staker addresses to make reward distribution OOG"],
                "Use pull-based reward claiming. Avoid iterating over all stakers.",
                []),
            ProtocolVulnCategory("Flash Loan Attacks", "flash-loan-attacks",
                "Flash loans used to temporarily inflate stake and claim disproportionate rewards.",
                ["Reward snapshot at end-of-block balance"],
                ["Flash borrow staking token → stake → claim snapshot reward → unstake → repay"],
                "Use time-weighted average balance for reward allocation. Add stake lockups.",
                []),
            ProtocolVulnCategory("Incorrect Math Calculations", "incorrect-math-calculations",
                "Reward per share calculation errors cause under or over-distribution of rewards.",
                ["accumulator precision insufficient for small reward amounts"],
                ["Stake small amounts repeatedly to exploit rounding in reward accumulator"],
                "Use high-precision accumulators (1e18+ scale). Test with extreme values.",
                []),
            ProtocolVulnCategory("Oracle Price Manipulation", "oracle-price-manipulation",
                "Staked token price manipulable to claim outsized rewards tied to token value.",
                ["APR calculated from spot staking token price"],
                ["Flash manipulate price → trigger high-APR reward period → collect → repay"],
                "Decouple reward rates from spot price. Use TWAP if price-linked rewards needed.",
                []),
            ProtocolVulnCategory("Reentrancy", "reentrancy",
                "Reentrant claims during reward token transfer allow double-claiming.",
                ["reward token transfer before pendingRewards zeroed"],
                ["Re-enter claimReward() via ERC-777 callback before balance updated"],
                "Zero out pending rewards before transfer. ReentrancyGuard.",
                ["SWC-107"]),
            ProtocolVulnCategory("Reward Distribution Flaws", "reward-distribution-flaws",
                "Incorrect per-user reward allocation due to snapshot timing or accumulator errors.",
                ["Global rewardPerShare not updated before user action"],
                ["Stake just after large reward injection without updating user's rewardDebt"],
                "Update global accumulator before any user stake/unstake/claim operation.",
                []),
            ProtocolVulnCategory("Vault Share Inflation First Depositor", "vault-share-inflation-first-depositor",
                "First staker sets share price; share inflation allows stealing subsequent stakers' funds.",
                ["shares = amount * totalShares / totalStaked where totalStaked can be donated"],
                ["Donate staking token → inflate ratio → next staker gets 0 shares"],
                "Virtual shares. Enforce minimum initial stake.",
                []),
        ],
    ),

    # ── GOVERNANCE / DAO ──────────────────────────────────────────────────────
    "governance": ProtocolType(
        name="Governance / DAO",
        slug="governance",
        description="On-chain governance systems including voting, proposals, and timelocks.",
        categories=[
            ProtocolVulnCategory("Flash Loan Governance Attack", "flash-loan-governance",
                "Governance tokens borrowed via flash loan to influence votes or quorum.",
                ["Voting power snapshot at vote time, not proposal creation"],
                ["Flash borrow tokens → vote on malicious proposal → repay"],
                "Snapshot voting power at proposal creation block. Require token lock period.",
                []),
            ProtocolVulnCategory("Proposal Front-Running", "proposal-front-running",
                "Attacker front-runs governance proposal to extract value before safeguards apply.",
                ["No delay between proposal creation and activation"],
                ["See governance proposal to list token → front-run to buy before listing"],
                "Require minimum timelock between proposal submission and activation.",
                []),
            ProtocolVulnCategory("Quorum Manipulation", "quorum-manipulation",
                "Quorum threshold too low or manipulable to pass proposals with minority stake.",
                ["Low quorum (e.g., 1% of supply) enables minority takeover"],
                ["Accumulate 1% of supply → vote with no opposition due to low participation → pass malicious proposal"],
                "Set meaningful quorum thresholds (≥4% of circulating supply). Require minimum participation.",
                []),
            ProtocolVulnCategory("Timelock Bypass", "timelock-bypass",
                "Timelock mechanism bypassed via emergency functions or incorrect delay calculation.",
                ["emergency pause can execute without timelock", "delay calculated from wrong timestamp"],
                ["Use emergency function to bypass timelock and execute malicious proposal immediately"],
                "Audit all execution paths. Emergency functions should only pause, not execute.",
                []),
            ProtocolVulnCategory("Vote Delegation Manipulation", "vote-delegation-manipulation",
                "Delegated voting power manipulable to concentrate governance control.",
                ["Mass delegation accepted without cooldown"],
                ["Create many addresses → delegate all to one attacker → at snapshot claim all voting power"],
                "Rate limit delegation. Require delegation cooldown period.",
                []),
        ],
    ),

    # ── NFT MARKETPLACE ───────────────────────────────────────────────────────
    "nft-marketplace": ProtocolType(
        name="NFT Marketplace",
        slug="nft-marketplace",
        description="Protocols for listing, bidding, and trading NFTs.",
        categories=[
            ProtocolVulnCategory("Access Control and Privilege Escalation", "access-control-and-privilege-escalation",
                "Admin functions for fee setting or listing cancellation accessible to non-admins.",
                ["setMarketplaceFee() without admin guard"],
                ["Set fee to 0 → trade with no fee → set back"],
                "Strict RBAC on all admin functions.",
                []),
            ProtocolVulnCategory("Front Running and MEV", "front-running-and-mev",
                "NFT bids and listings front-runnable to snipe underpriced NFTs or cancel competitor bids.",
                ["Large NFT offer visible in mempool before acceptance"],
                ["See large bid in mempool → front-run with exact amount to steal the buy"],
                "Use commit-reveal for bids. Flash-loan protection for listings.",
                []),
            ProtocolVulnCategory("Reentrancy Vulnerabilities", "reentrancy-vulnerabilities",
                "ERC-721 safeTransfer callbacks allow reentrancy into marketplace during sale.",
                ["onERC721Received hook called during sale before proceeds distributed"],
                ["Re-enter buy() via NFT callback to purchase same NFT twice at same price"],
                "Distribute proceeds before transferring NFT, or apply ReentrancyGuard.",
                ["SWC-107"]),
            ProtocolVulnCategory("Signature Validation and Replay", "signature-validation-and-replay",
                "Listing signatures replayable after cancellation or on different chains.",
                ["EIP-712 signature without nonce invalidation", "chainId not in domain separator"],
                ["After seller cancels listing, replay old signature to force sale at low price"],
                "Nonce-based cancellation. Include chainId in listing signatures.",
                []),
            ProtocolVulnCategory("Order Validation and Matching", "order-validation-and-matching",
                "Order matching logic allows partial fills, price manipulation, or unintended trades.",
                ["Price calculation susceptible to manipulation when token price used"],
                ["Craft order parameters that match at attacker-controlled price"],
                "Strict price/amount validation. Prevent any variance from order parameters.",
                []),
            ProtocolVulnCategory("Gas Griefing and Denial of Service", "gas-griefing-and-denial-of-service",
                "Attacker causes OOG errors or blocks listings by manipulating gas consumption.",
                ["Unbounded loop over offers", "External call to potentially reverting contract"],
                ["Place many offers triggering gas exhaustion in offer cleanup"],
                "Cap number of active offers per listing. Use pull-payment pattern.",
                []),
        ],
    ),

    # ── ORACLE ────────────────────────────────────────────────────────────────
    "oracle": ProtocolType(
        name="Oracle",
        slug="oracle",
        description="Price feed and oracle protocols providing on-chain data.",
        categories=[
            ProtocolVulnCategory("Stale Oracle Price Data", "stale-oracle-price-data",
                "Oracle price not checked for freshness, allowing stale data to be used in critical calculations.",
                ["latestRoundData() used without checking updatedAt vs block.timestamp"],
                ["Oracle paused → stale price persists → protocol uses wrong collateral value"],
                "Assert updatedAt + maxStaleness > block.timestamp. Use sequencer uptime feed on L2.",
                ["https://docs.chain.link/data-feeds"]),
            ProtocolVulnCategory("TWAP Oracle Miscalculation", "twap-oracle-miscalculation",
                "Incorrect TWAP implementation causes wrong time-averaged price.",
                ["TWAP window too short (< 5 minutes)", "TWAP cumulative price not correctly normalized"],
                ["Short TWAP window allows manipulation within single block or small set of blocks"],
                "Use minimum 30-minute TWAP window. Validate cumulative price update logic.",
                []),
            ProtocolVulnCategory("Oracle Price Manipulation via Reserves", "oracle-price-manipulation-via-reserves",
                "Reserve-based oracle price (Uniswap V2) manipulable via single large trade.",
                ["getReserves() used directly for price calculation"],
                ["Flash swap manipulates reserves → manipulated price used → revert swap"],
                "Never use spot reserve ratio as price. Use TWAP or external oracle.",
                []),
            ProtocolVulnCategory("Incorrect Price Feed Decimal Handling", "incorrect-price-feed-decimal-handling",
                "Chainlink price feed decimals assumed to be 8, causing precision errors with non-standard feeds.",
                ["price assumed to be 1e8 scale", "No feed.decimals() call to normalize"],
                ["ETH/USD feed is 8 decimals but ETH/JPY might differ → wrong price calculation"],
                "Always call feed.decimals() and normalize accordingly.",
                []),
            ProtocolVulnCategory("Frontrunning and Slippage Protection", "frontrunning-and-slippage-protection",
                "Oracle update transactions front-runnable to exploit price discrepancy window.",
                ["Oracle update via standard mempool", "No slippage protection during oracle update window"],
                ["Observe oracle update → front-run transactions before/after at old/new price"],
                "Use private mempool for oracle updates. Implement post-update lockout period.",
                []),
        ],
    ),

    # ── ACCOUNT ABSTRACTION (ERC-4337) ────────────────────────────────────────
    "account-abstraction": ProtocolType(
        name="Account Abstraction (ERC-4337)",
        slug="account-abstraction",
        description="ERC-4337 bundler, paymaster, and smart wallet contracts.",
        categories=[
            ProtocolVulnCategory("Paymaster Exploitation", "paymaster-exploitation",
                "Paymaster validates and sponsors UserOps in ways that can be exploited.",
                ["Paymaster sponsoring any UserOp without per-user limits", "Gas price griefing against paymaster"],
                ["Submit expensive UserOps to drain paymaster's deposit without real intent"],
                "Add per-user rate limits and stake requirements for sponsored operations.",
                ["https://eips.ethereum.org/EIPS/eip-4337"]),
            ProtocolVulnCategory("Signature Validation Bypass", "signature-validation-bypass",
                "smart wallet signature validation flaws allow unauthorized operation execution.",
                ["validateUserOp() accepts malformed signatures", "Nonce replay in smart wallet"],
                ["Replay signed UserOp to execute transaction twice"],
                "Strict signature validation. Nonce management per-wallet.",
                []),
            ProtocolVulnCategory("Bundler Manipulation", "bundler-manipulation",
                "Bundler can reorder, censor, or extract value from UserOp bundles.",
                ["No protection against bundler MEV extraction", "Bundler can drop critical ops"],
                ["Bundler reorders ops to sandwich user's DeFi interaction"],
                "Use decentralized bundler networks. Implement bundler reputation systems.",
                []),
            ProtocolVulnCategory("Factory and Initialization", "factory-and-initialization",
                "Wallet factory initialization flaws allow account takeover before first use.",
                ["Counterfactual address exploitable before deployment", "initCode can be front-run"],
                ["Front-run wallet deployment with different initCode to create wallet with attacker's key"],
                "Include owner's address in salt used for CREATE2. Verify initCode matches expected.",
                []),
        ],
    ),
}


# ── Protocol type detection ───────────────────────────────────────────────────

PROTOCOL_KEYWORDS: dict[str, list[str]] = {
    "algo-stables": ["algorithmic", "algo stable", "stablecoin", "peg", "seigniorage", "rebase", "algorithmic stablecoin"],
    "bridge": ["bridge", "cross-chain", "cross chain", "l1-l2", "layer2 bridge", "ibc", "relay", "message passing", "ccip", "layerzero", "wormhole", "nomad"],
    "cdp": ["cdp", "collateralized debt", "vault", "stability fee", "maker", "dai", "liquidation ratio", "collateral ratio"],
    "dexes": ["dex", "amm", "swap", "uniswap", "curve", "balancer", "liquidity pool", "automated market maker", "order book", "trading"],
    "lending": ["lending", "borrowing", "aave", "compound", "collateral", "health factor", "liquidation", "atokens", "ctokens", "interest rate"],
    "liquid-staking": ["liquid staking", "lst", "steth", "lido", "reth", "cbeth", "liquid stake", "validator", "beacon chain"],
    "yield-aggregator": ["yield aggregator", "auto-compound", "yearn", "harvest", "strategy", "vault strategy", "yield optimizer"],
    "staking-pool": ["staking", "stake pool", "reward distribution", "rewards", "governance staking", "lockup"],
    "governance": ["governance", "dao", "voting", "proposal", "timelock", "snapshot", "quorum", "delegat"],
    "nft-marketplace": ["nft marketplace", "opensea", "listing", "bid", "auction", "royalty", "erc721 marketplace"],
    "oracle": ["oracle", "price feed", "chainlink", "twap", "price manipulation", "data feed"],
    "account-abstraction": ["erc-4337", "account abstraction", "bundler", "paymaster", "userop", "smart wallet", "entrypoint"],
}


def detect_protocol_type(text: str) -> list[str]:
    """Detect which protocol types are relevant for a given target description."""
    text_lower = text.lower()
    detected = []
    for ptype, keywords in PROTOCOL_KEYWORDS.items():
        if any(kw in text_lower for kw in keywords):
            detected.append(ptype)
    return detected if detected else ["dexes", "lending"]  # default to most common


def get_protocol_checklist(protocol_type: str) -> str:
    """Get vulnerability checklist for a specific protocol type."""
    pt = PROTOCOL_INDEX.get(protocol_type)
    if not pt:
        return f"Protocol type '{protocol_type}' not found."
    return pt.get_checklist()


def get_multi_protocol_checklist(protocol_types: list[str]) -> str:
    """Get combined vulnerability checklist for multiple protocol types."""
    lines = [f"## Protocol-Specific Vulnerability Checklist\n"]
    lines.append(f"Detected protocol type(s): {', '.join(protocol_types)}\n")
    seen_categories: set[str] = set()
    for ptype in protocol_types:
        pt = PROTOCOL_INDEX.get(ptype)
        if not pt:
            continue
        lines.append(f"\n### {pt.name} ({len(pt.categories)} categories)")
        for cat in pt.categories:
            if cat.name not in seen_categories:
                lines.append(f"- [ ] **{cat.name}**: {cat.description[:80]}...")
                seen_categories.add(cat.name)
    return "\n".join(lines)


def get_all_protocol_types() -> list[str]:
    """Return all available protocol type slugs."""
    return list(PROTOCOL_INDEX.keys())


def get_category_detail(protocol_type: str, category_name: str) -> str:
    """Get full detail for a specific vulnerability category."""
    pt = PROTOCOL_INDEX.get(protocol_type)
    if not pt:
        return f"Protocol type '{protocol_type}' not found."
    cat = pt.get_category(category_name)
    if not cat:
        return f"Category '{category_name}' not found in {protocol_type}."
    lines = [
        f"## {cat.name}",
        f"\n**Description:** {cat.description}",
        f"\n**Detection Hints:**",
    ]
    for h in cat.detection_hints:
        lines.append(f"  - {h}")
    if cat.attack_patterns:
        lines.append(f"\n**Attack Patterns:**")
        for p in cat.attack_patterns:
            lines.append(f"  - {p}")
    if cat.remediation:
        lines.append(f"\n**Remediation:** {cat.remediation}")
    if cat.references:
        lines.append(f"\n**References:** {', '.join(cat.references)}")
    return "\n".join(lines)


# ── Full index stats ──────────────────────────────────────────────────────────
def index_stats() -> str:
    total = sum(len(pt.categories) for pt in PROTOCOL_INDEX.values())
    lines = [f"Protocol Vulnerabilities Index — {len(PROTOCOL_INDEX)} protocol types, {total} categories\n"]
    for slug, pt in PROTOCOL_INDEX.items():
        lines.append(f"  {pt.name:<35} {len(pt.categories):>3} categories")
    return "\n".join(lines)
